### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by snow2k9** [Shape-and-Shift/maps#2]
Hey, 

installed your plugin and embedded it. Shopware 6.1.4
Backend works like a charm
Frontend throws and doesn't display anything
```
Uncaught TypeError: Super expression must either be null or a function
    at _inherits (Y9E2:21)
    at eval (sas-maps.plugin.js?a41f:6)
    at eval (sas-maps.plugin.js?a41f:6)
    at Module.Y9E2 (all.js:41)
    at i (all.js:4)
    at eval (main.js?912d:1)
    at Module.KAfm (all.js:18)
    at i (all.js:4)
    at n (all.js:4)
    at Array.r [as push] (all.js:4)
```

**Comment by ChristopherDosin** [comment]
Hey @snow2k9,

thanks for reporting the issue, i'll have a look at it tomorrow.

In the meantime: To figure out the issue, can you tell me the steps to reproduce the issue?
Did you entered the mapbox API key within the plugin settings, did you entered an address within the maps element etc.?

**Comment by snow2k9** [comment]
- Downloaded ZIP from Github
- Uploaded to Shopware
- Activated plugin
- Configured API key 
- Created maps element with address through search
- Some messup with mapbox domain restrictions
- Removed domain restrictions from mapbox
- working backend

**Comment by ChristopherDosin** [comment]
@snow2k9 Sorry for the late reply. I could reproduce the error and fixed it.
Also another issue #3 with Shopware version 6.2

Could you please download the latest release and check if it's working for you now?

**Comment by snow2k9** [comment]
everything fixed
works like a charm, thanks
